defmodule PrefixedIdDemo.Repo.Migrations.AddPrefixedIdDemo do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:todos, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :title, :text, null: false
      add :done, :boolean, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id, :uuid, null: false
    end

    create table(:teams, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:projects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:todos) do
      modify :project_id,
             references(:projects,
               column: :id,
               name: "todos_project_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:todos, [:project_id])

    alter table(:projects) do
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :team_id,
          references(:teams,
            column: :id,
            name: "projects_team_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create index(:projects, [:team_id])
  end

  def down do
    drop_if_exists index(:projects, [:team_id])

    drop constraint(:projects, "projects_team_id_fkey")

    alter table(:projects) do
      remove :team_id
      remove :updated_at
      remove :inserted_at
      remove :name
    end

    drop_if_exists index(:todos, [:project_id])

    drop constraint(:todos, "todos_project_id_fkey")

    alter table(:todos) do
      modify :project_id, :uuid
    end

    drop table(:projects)

    drop table(:teams)

    drop table(:todos)
  end
end
