// Generated by AshTypescript - RPC Actions
// Do not edit this file manually


import type { AshRpcError, InferResult, ProjectFilterInput, ProjectResourceSchema, ProjectSortField, SortString, TeamFilterInput, TeamResourceSchema, TeamSortField, TodoFilterInput, TodoResourceSchema, TodoSortField, UUIDv7, UnifiedFieldSelection } from "./ash_types";
export type * from "./ash_types";

// Helper Functions

/**
 * Configuration options for action RPC requests
 */
export interface ActionConfig {
  // Request data
  input?: Record<string, any>;
  identity?: any;
  fields?: Array<string | Record<string, any>>; // Field selection
  filter?: Record<string, any>; // Filter options (for reads)
  sort?: string | string[]; // Sort options
  page?:
    | {
        // Offset-based pagination
        limit?: number;
        offset?: number;
        count?: boolean;
      }
    | {
        // Keyset pagination
        limit?: number;
        after?: string;
        before?: string;
      };

  // Metadata
  metadataFields?: ReadonlyArray<string>;

  // HTTP customization
  headers?: Record<string, string>; // Custom headers
  fetchOptions?: RequestInit; // Fetch options (signal, cache, etc.)
  customFetch?: (
    input: RequestInfo | URL,
    init?: RequestInit,
  ) => Promise<Response>;

  // Multitenancy
  tenant?: string; // Tenant parameter

  // Hook context
  hookCtx?: Record<string, any>;
}




/**
 * Gets the CSRF token from the page's meta tag
 * Returns null if no CSRF token is found
 */
export function getPhoenixCSRFToken(): string | null {
  return document
    ?.querySelector("meta[name='csrf-token']")
    ?.getAttribute("content") || null;
}

/**
 * Builds headers object with CSRF token for Phoenix applications
 * Returns headers object with X-CSRF-Token (if available)
 */
export function buildCSRFHeaders(headers: Record<string, string> = {}): Record<string, string> {
  const csrfToken = getPhoenixCSRFToken();
  if (csrfToken) {
    headers["X-CSRF-Token"] = csrfToken;
  }

  return headers;
}

/**
 * Internal helper function for making action RPC requests
 * Handles hooks, request configuration, fetch execution, and error handling
 * @param config Configuration matching ActionConfig
 */
export async function executeActionRpcRequest<T>(
  payload: Record<string, any>,
  config: ActionConfig
): Promise<T> {
    const processedConfig = config;

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...processedConfig.headers,
    ...config.headers,
  };

  const fetchFunction = config.customFetch || processedConfig.customFetch || fetch;
  const fetchOptions: RequestInit = {
    ...processedConfig.fetchOptions,
    ...config.fetchOptions,
    method: "POST",
    headers,
    body: JSON.stringify(payload),
  };

  const response = await fetchFunction("/rpc/run", fetchOptions);
  const result = response.ok ? await response.json() : null;


  if (!response.ok) {
    return {
      success: false,
      errors: [
        {
          type: "network_error",
          message: `Network request failed: ${response.statusText}`,
          shortMessage: "Network error",
          vars: { statusCode: response.status, statusText: response.statusText },
          fields: [],
          path: [],
          details: { statusCode: response.status }
        }
      ],
    } as T;
  }

  return result as T;
}









export type CreateProjectInput = {
  name: string;
  teamId: string;
};

export type CreateProjectFields = UnifiedFieldSelection<ProjectResourceSchema>[];

export type InferCreateProjectResult<
  Fields extends CreateProjectFields | undefined,
> = InferResult<ProjectResourceSchema, Fields>;

export type CreateProjectResult<Fields extends CreateProjectFields | undefined = undefined> = | { success: true; data: InferCreateProjectResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Project
 *
 * @ashActionType :create
 */
export async function createProject<Fields extends CreateProjectFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: CreateProjectInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CreateProjectResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "create_project",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CreateProjectResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


export type GetProjectInput = {
  id: UUIDv7;
};

export type GetProjectFields = UnifiedFieldSelection<ProjectResourceSchema>[];
export type InferGetProjectResult<
  Fields extends GetProjectFields,
> = InferResult<ProjectResourceSchema, Fields>;

export type GetProjectResult<Fields extends GetProjectFields> = | { success: true; data: InferGetProjectResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Project records
 *
 * @ashActionType :read
 */
export async function getProject<Fields extends GetProjectFields>(
  config: {
  tenant?: string;
  input: GetProjectInput;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GetProjectResult<Fields>> {
  const payload = {
    action: "get_project",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<GetProjectResult<Fields>>(
    payload,
    config
  );
}


export type ListProjectsFields = UnifiedFieldSelection<ProjectResourceSchema>[];
export type InferListProjectsResult<
  Fields extends ListProjectsFields,
> = Array<InferResult<ProjectResourceSchema, Fields>>;

export type ListProjectsResult<Fields extends ListProjectsFields> = | { success: true; data: InferListProjectsResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Project records
 *
 * @ashActionType :read
 */
export async function listProjects<Fields extends ListProjectsFields>(
  config: {
  tenant?: string;
  fields: Fields;
  filter?: ProjectFilterInput;
  sort?: SortString<ProjectSortField> | SortString<ProjectSortField>[];
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ListProjectsResult<Fields>> {
  const payload = {
    action: "list_projects",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  };

  return executeActionRpcRequest<ListProjectsResult<Fields>>(
    payload,
    config
  );
}


export type CreateTeamInput = {
  name: string;
};

export type CreateTeamFields = UnifiedFieldSelection<TeamResourceSchema>[];

export type InferCreateTeamResult<
  Fields extends CreateTeamFields | undefined,
> = InferResult<TeamResourceSchema, Fields>;

export type CreateTeamResult<Fields extends CreateTeamFields | undefined = undefined> = | { success: true; data: InferCreateTeamResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Team
 *
 * @ashActionType :create
 */
export async function createTeam<Fields extends CreateTeamFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: CreateTeamInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CreateTeamResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "create_team",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CreateTeamResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


export type GetTeamInput = {
  id: UUIDv7;
};

export type GetTeamFields = UnifiedFieldSelection<TeamResourceSchema>[];
export type InferGetTeamResult<
  Fields extends GetTeamFields,
> = InferResult<TeamResourceSchema, Fields>;

export type GetTeamResult<Fields extends GetTeamFields> = | { success: true; data: InferGetTeamResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Team records
 *
 * @ashActionType :read
 */
export async function getTeam<Fields extends GetTeamFields>(
  config: {
  tenant?: string;
  input: GetTeamInput;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GetTeamResult<Fields>> {
  const payload = {
    action: "get_team",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<GetTeamResult<Fields>>(
    payload,
    config
  );
}


export type ListTeamsFields = UnifiedFieldSelection<TeamResourceSchema>[];
export type InferListTeamsResult<
  Fields extends ListTeamsFields,
> = Array<InferResult<TeamResourceSchema, Fields>>;

export type ListTeamsResult<Fields extends ListTeamsFields> = | { success: true; data: InferListTeamsResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Team records
 *
 * @ashActionType :read
 */
export async function listTeams<Fields extends ListTeamsFields>(
  config: {
  tenant?: string;
  fields: Fields;
  filter?: TeamFilterInput;
  sort?: SortString<TeamSortField> | SortString<TeamSortField>[];
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ListTeamsResult<Fields>> {
  const payload = {
    action: "list_teams",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  };

  return executeActionRpcRequest<ListTeamsResult<Fields>>(
    payload,
    config
  );
}


export type CreateTodoInput = {
  title: string;
  done?: boolean | null;
  projectId: string;
};

export type CreateTodoFields = UnifiedFieldSelection<TodoResourceSchema>[];

export type InferCreateTodoResult<
  Fields extends CreateTodoFields | undefined,
> = InferResult<TodoResourceSchema, Fields>;

export type CreateTodoResult<Fields extends CreateTodoFields | undefined = undefined> = | { success: true; data: InferCreateTodoResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Todo
 *
 * @ashActionType :create
 */
export async function createTodo<Fields extends CreateTodoFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: CreateTodoInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CreateTodoResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "create_todo",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CreateTodoResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


export type GetTodoInput = {
  id: UUIDv7;
};

export type GetTodoFields = UnifiedFieldSelection<TodoResourceSchema>[];
export type InferGetTodoResult<
  Fields extends GetTodoFields,
> = InferResult<TodoResourceSchema, Fields>;

export type GetTodoResult<Fields extends GetTodoFields> = | { success: true; data: InferGetTodoResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Todo records
 *
 * @ashActionType :read
 */
export async function getTodo<Fields extends GetTodoFields>(
  config: {
  tenant?: string;
  input: GetTodoInput;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GetTodoResult<Fields>> {
  const payload = {
    action: "get_todo",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<GetTodoResult<Fields>>(
    payload,
    config
  );
}


export type ListTodosFields = UnifiedFieldSelection<TodoResourceSchema>[];
export type InferListTodosResult<
  Fields extends ListTodosFields,
> = Array<InferResult<TodoResourceSchema, Fields>>;

export type ListTodosResult<Fields extends ListTodosFields> = | { success: true; data: InferListTodosResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Todo records
 *
 * @ashActionType :read
 */
export async function listTodos<Fields extends ListTodosFields>(
  config: {
  tenant?: string;
  fields: Fields;
  filter?: TodoFilterInput;
  sort?: SortString<TodoSortField> | SortString<TodoSortField>[];
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ListTodosResult<Fields>> {
  const payload = {
    action: "list_todos",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  };

  return executeActionRpcRequest<ListTodosResult<Fields>>(
    payload,
    config
  );
}

